---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rubim.
--- DateTime: 01/06/2018 02:34
---

local pvpRub = true
rotationMode = none
if pvp then
    local pvpHelper = CreateFrame("Frame", "DebugFrame", UIParent)
    local rotationText = pvpHelper:CreateFontString("DebugText", "OVERLAY")
    local OneTimeRubim = nil
    local event = function()
        if OneTimeRubim == nil then
            pvpHelper:SetWidth(240)
            pvpHelper:SetHeight(40)
            pvpHelper:SetPoint("CENTER")-- Baseado no chat?
            local tex = pvpHelper:CreateTexture("BACKGROUND")
            tex:SetAllPoints()
            tex:SetTexture(0, 0, 0);
            tex:SetAlpha(0.5)
            OneTimeRubim = 1
        end

        rotationText:SetFontObject(GameFontNormalSmall)
        rotationText:SetJustifyH("CENTER") --
        rotationText:SetPoint("CENTER", pvpHelper, "CENTER", 0, 0) -- Centralizado sempre / TODO Salvar localização em variavél.
        rotationText:SetFont("Fonts\\FRIZQT__.TTF", 20)
        rotationText:SetShadowOffset(1, -1)
        rotationText:SetText("Hello")

        local t = GetTime()
        pvpHelper:SetScript("OnUpdate", function()
            --se tiver com problemas, colocar um delay usando o GetTime()
            --if t - GetTime() <= 0.2 then
            rotationText:SetText(rotationMode)
            --t = GetTime()
            --		end
        end)

        pvpHelper:SetMovable(true)
        pvpHelper:EnableMouse(true)
        pvpHelper:SetScript("OnMouseDown", function(self, button)
            if button == "LeftButton" and not self.isMoving then
                self:StartMoving();
                self.isMoving = true;
            end
        end)
        pvpHelper:SetScript("OnMouseUp", function(self, button)
            if button == "LeftButton" and self.isMoving then
                local arg1, _, arg2, arg3, arg4 = pvpHelper:GetPoint()
                self:StopMovingOrSizing();
                self.isMoving = false;
            end
        end)
        pvpHelper:SetScript("OnHide", function(self)
            if (self.isMoving) then
                self:StopMovingOrSizing();
                self.isMoving = false;
            end
        end)

    end

    local total = 0

    local function onUpdate(self, elapsed)
        total = total + elapsed
        if total >= 1 then

            total = 0
        end
    end

    local f = CreateFrame("frame")
    f:SetScript("OnUpdate", onUpdate)

    pvpHelper:SetScript("OnEvent", event)
    pvpHelper:RegisterEvent("PLAYER_LOGIN")

end