---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rubim.
--- DateTime: 02/06/2018 12:53
---
local RubimRH = LibStub("AceAddon-3.0"):GetAddon("RubimRH")

_G["RubimRH"] = RubimRH
function RubimRH.CDToggle()
    PlaySound(891, "Master");
    if useCD == false then
        varClass.cooldown = true
        useCD = true
    else
        useCD = false
        varClass.cooldown = false
    end
    print("|cFF69CCF0CD".. "|r: |cFF00FF00" .. tostring(useCD))
end

local options, configOptions = nil, {}
--[[ This options table is used in the GUI config. ]]--
local function getOptions()
    if not options then
        options = {
            type = "group",
            name = "RubimRH",
            args = {
                mainOptions = {
                    order = 1,
                    type = "group",
                    name = "General",
                    childGroups = "tab",
                    args = {
                        general = {
                            order = 1,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "General Config",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.mo[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.mo[key] = value
                            end,
                            args = {
                                cooldownbind = {
                                    order = 1,
                                    type = "keybinding",
                                    get = function() return GetBindingKey("Cooldown Toggle")    end,
                                    set = function(info, v) SetBinding(v, "Cooldown Toggle")    SaveBindings(GetCurrentBindingSet()) end,
                                    name = "Cooldowns"
                                },
                                interruptsbind = {
                                    order = 2,
                                    type = "keybinding",
                                    get = function() return GetBindingKey("Interrupt Toggle")    end,
                                    set = function(info, v) SetBinding(v, "Interrupt Toggle")    SaveBindings(GetCurrentBindingSet()) end,
                                    name = "Interrupts"
                                },
                            }
                        },
                    }
                },
                DeathKnight = {
                    order = 1,
                    type = "group",
                    name = "DK",
                    childGroups = "tab",
                    args = {
                        general = {
                            order = 1,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "General",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.dk[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.dk[key] = value
                            end,
                            args = {
                                cooldowns = {
                                    order = 1,
                                    type = "toggle",
                                    get = function() return useCD end,
                                    set = function(info, v) RubimRH.CDToggle() end,
                                    name = "Cooldowns"
                                },
                            }
                        },
                        dk = {
                            order = 2,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "Death Knight - Frost/Unholy",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.dk[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.dk[key] = value
                            end,
                            args = {
                                deathstrike = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Death Strike (Dark Succur)"
                                },
                            }
                        },
                    }
                },
                Warrior = {
                    order = 1,
                    type = "group",
                    name = "Warrior",
                    args = {
                        general = {
                            order = 1,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "General",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.wr[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.wr[key] = value
                            end,
                            args = {
                                cooldowns = {
                                    order = 1,
                                    type = "toggle",
                                    get = function() return useCD end,
                                    set = function(info, v) RubimRH.CDToggle() end,
                                    name = "Cooldowns"
                                },
                            }
                        },
                        wr = {
                            order = 2,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "Warrior - Arms",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.wr[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.wr[key] = value
                            end,
                            args = {
                                victoryrush = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Victory Rush"
                                },
                            }
                        },
                    }
                },
                Paladin = {
                    order = 1,
                    type = "group",
                    name = "General",
                    args = {
                        general = {
                            order = 1,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "General",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.pl[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.pl[key] = value
                            end,
                            args = {
                                cooldowns = {
                                    order = 1,
                                    type = "toggle",
                                    name = "Cooldowns"
                                },
                            }
                        },
                        prot = {
                            order = 2,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "Paladin - Protection",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.pl[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.pl[key] = value
                            end,
                            args = {
                                lightoftheprotector = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Light of the Protector"
                                },
                            }
                        },
                        ret = {
                            order = 3,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "Paladin - Retribution",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.pl[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.pl[key] = value
                            end,
                            args = {
                                justicarglory = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Justicar/Word of Glory"
                                },
                            }
                        },
                    }
                },
                Druid = {
                    order = 1,
                    type = "group",
                    name = "General",
                    args = {
                        general = {
                            order = 1,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "General",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.dr[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.dr[key] = value
                            end,
                            args = {
                                cooldowns = {
                                    order = 1,
                                    type = "toggle",
                                    name = "Cooldowns"
                                },
                            }
                        },
                        feral = {
                            order = 2,
                            type = "group",
                            childGroups = "tab",
                            inline = true,
                            name = "Druid - Feral",
                            get = function(info)
                                local key = info.arg or info[#info]
                                return RubimRH.db.profile.dr[key]
                            end,
                            set = function(info, value)
                                local key = info.arg or info[#info]
                                RubimRH.db.profile.dr[key] = value
                            end,
                            args = {
                                renewal = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Renewal"
                                },
                                regrowth = {
                                    order = 1,
                                    type = "range",
                                    min = 5,
                                    max = 95,
                                    step = 5,
                                    --fontSize = "medium",
                                    name = "Regrowth"
                                },
                            }
                        },
                    }
                }
            }
        }
        for k, v in pairs(configOptions) do
            options.args[k] = (type(v) == "function") and v() or v
        end
    end

    return options
end

local function openConfig()
    InterfaceOptionsFrame_OpenToCategory(RubimRH.optionsFrames.Profiles)
    InterfaceOptionsFrame_OpenToCategory(RubimRH.optionsFrames.RubimRH)
    InterfaceOptionsFrame:Raise()
end

function RubimRH:SetupOptions()
    self.optionsFrames = {}

    LibStub("AceConfigRegistry-3.0"):RegisterOptionsTable("RubimRH", getOptions)
    self.optionsFrames.RubimRH = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", nil, nil, "mainOptions")
    self.optionsFrames["Profiles"] = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", "Death Knight", "RubimRH", "DeathKnight")
    self.optionsFrames["Profiles"] = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", "Paladin", "RubimRH", "Paladin")
    self.optionsFrames["Profiles"] = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", "Warrior", "RubimRH", "Warrior")
    self.optionsFrames["Profiles"] = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", "Druid", "RubimRH", "Druid")
    configOptions["Profiles"] = LibStub("AceDBOptions-3.0"):GetOptionsTable(self.db)
    self.optionsFrames["Profiles"] = LibStub("AceConfigDialog-3.0"):AddToBlizOptions("RubimRH", "Profiles", "RubimRH", "Profiles")

    LibStub("AceConsole-3.0"):RegisterChatCommand("RubimRH", openConfig)
end